### PR TITLE
Fix wordpress example due to change in k8s 1.1.7

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by dustymabe** [comment]
Could you update the git commit message (not the one line, but the paragraph below it) to explain what the problem was and how you fixed it? This is good for context when looking through the commits. 

After you do that then MERGE!! LGTM

**Comment by cdrage** [comment]
@dustymabe I ran into some issues bringing this up with Kubernetes 1.2.0alpha. I'm going to have another look at this again.

**Comment by dustymabe** [comment]
Not really sure why this was closed? The file change resolved the issue I thought?

**Comment by dustymabe** [comment]
@cdrage - could you re-evaluate why you closed this PR? I don't think you meant to close 58, but rather 59.

**Comment by dustymabe** [comment]
FYI - ci is still failing with: 

```
error validating "build/artifacts/kubernetes/.wordpress-service.yaml": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by cdrage** [comment]
Oh, woops. Yeah. I meant to close 59 not 58

**Comment by cdrage** [comment]
So our wordpress example is almost _the exact_ same as kubernetes' example: https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd

But I'm getting an odd error now:

```
dev/nulecule-library/wordpress-centos7-atomicapp  fix-wordpress-port ✗                                                                                                                                                                                  7d ⚑  
▶ kubectl get po
NAME                   READY     STATUS             RESTARTS   AGE
k8s-etcd-127.0.0.1     1/1       Running            0          11m
k8s-master-127.0.0.1   4/4       Running            0          12m
k8s-proxy-127.0.0.1    1/1       Running            0          11m
mariadb                1/1       Running            0          1m
wordpress              0/1       CrashLoopBackOff   3          1m

▶ kubectl describe po wordpress
Name:                           wordpress
Namespace:                      default
Image(s):                       wordpress
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Tue, 01 Mar 2016 09:23:06 -0500
Labels:                         name=wordpress-frontend
Status:                         Running
Reason:
Message:
IP:                             172.17.0.5
Replication Controllers:        <none>
Containers:
  wordpress:
    Container ID:               docker://425214e8398eac59fbc18cdd46eade282a5fa8e9efbd0d1ade8c0c0d266e513b
    Image:                      wordpress
    Image ID:                   docker://sha256:d97c3c4a32f3e52c8290c5568a4eed1beacb6617908e488d0a8935770f0b3253
    State:                      Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Tue, 01 Mar 2016 09:23:21 -0500
      Finished:                 Tue, 01 Mar 2016 09:23:22 -0500
    Last Termination State:     Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Tue, 01 Mar 2016 09:23:09 -0500
      Finished:                 Tue, 01 Mar 2016 09:23:09 -0500
    Ready:                      False
    Restart Count:              2
    Environment Variables:
      WORDPRESS_DB_USER:        test
      WORDPRESS_DB_PASSWORD:    test
      WORDPRESS_DB_NAME:        test
      WORDPRESS_DB_HOST:        mariadb:3306
Conditions:
  Type          Status
  Ready         False 
Volumes:
  default-token-wwpx6:
    Type:       Secret (a secret that should populate this volume)
    SecretName: default-token-wwpx6
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                   Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────                   ──────          ───────
  22s           22s             1       {default-scheduler }                                    Scheduled       Successfully assigned wordpress to 127.0.0.1
  21s           21s             1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Created         Created container with docker id dea13554878a
  20s           20s             1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Started         Started container with docker id dea13554878a
  19s           19s             1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Started         Started container with docker id 3dc6ff96145c
  19s           19s             1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Created         Created container with docker id 3dc6ff96145c
  18s           17s             2       {kubelet 127.0.0.1}                                     FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "wordpress" with CrashLoopBackOff: "Back-off 10s restarting failed container=wordpress pod=wordpress_default(1da5e845-dfb9-11e5-8137-54ee754d2b5e)"

  21s   7s      3       {kubelet 127.0.0.1}     spec.containers{wordpress}      Pulled          Container image "wordpress" already present on machine
  7s    7s      1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Created         Created container with docker id 425214e8398e
  7s    7s      1       {kubelet 127.0.0.1}     spec.containers{wordpress}      Started         Started container with docker id 425214e8398e
  18s   6s      3       {kubelet 127.0.0.1}     spec.containers{wordpress}      BackOff         Back-off restarting failed docker container
  6s    6s      1       {kubelet 127.0.0.1}                                     FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "wordpress" with CrashLoopBackOff: "Back-off 20s restarting failed container=wordpress pod=wordpress_default(1da5e845-dfb9-11e5-8137-54ee754d2b5e)"

dev/nulecule-library/wordpress-centos7-atomicapp  fix-wordpress-port ✗                                                                                                                                                                                  7d ⚑  
▶ kubectl logs wordpress          
2016-03-01 14:24:29,044 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): 10.0.0.1
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2016-03-01 14:24:29,058 - requests.packages.urllib3.connectionpool - DEBUG - "GET /oapi HTTP/1.1" 401 13
usage: atomicapp {run,fetch,stop,genanswers} ...
atomicapp: error: too few arguments

```

:confused:

**Comment by dustymabe** [comment]
@cdrage are you still having an error? after updating to newer kube (i.e. merging my changes into adb-tests repo and thus moving to the newer kube that you instantiated) the kubernetes test now passes

**Comment by cdrage** [comment]
@dustymabe 
Yes, I'm getting a crashloopback error :( still trying to diagnose it.

**Comment by cdrage** [comment]
@dustymabe @goern

Has wordpress always been broken?

Just got this error with mariadb:

```
▶ kubectl logs wordpress
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by cdrage** [comment]
nvm! seems to be not deploying skydns properly

**Comment by cdrage** [comment]
@dustymabe Okay. This works!

```
▶ kubectl describe po wordpress
Name:           wordpress
Namespace:      default
Node:           127.0.0.1/127.0.0.1
Start Time:     Thu, 07 Apr 2016 09:29:26 -0400
Labels:         name=wordpress-frontend
Status:         Running
IP:             172.17.0.7

▶ telnet 172.17.0.7 80
Trying 172.17.0.7...
Connected to 172.17.0.7.
Escape character is '^]'.
```

If you want to try it, feel free!

**Comment by dustymabe** [comment]
your commit message:

```
Kubernetes has not changed the way that we use both port and target
port. Kubernetes manages the master port-list. By removing "targetport"
Kubernetes will automatically point to port :80 now.
```

I'm confused by what you mean exactly with the first sentence. Can you try to clear it up?

**Comment by cdrage** [comment]
@dustymabe updated the commit message

**Comment by dustymabe** [comment]
LGTM

**Pull request merged**
