### PR TITLE
Fix postgres pod / service files

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
Forgot I was merging from **my** master, ha. Created a new branch and PR for this in light of #58

**Comment by cdrage** [comment]
ping @dustymabe updatd with your comments :) I should of split the commits up

**Comment by dustymabe** [comment]
so you are still moving around things and making changes in the same commit. The commit message actually states it `Reorganize postgres pod file metadata, remove id:`. I would prefer it to be:

commit 1:

```
postgresql: remove id from pod specification

`id` is not a valid part of the v1 pod spec
```

commit 2:

```
postgresql: reorganize pod definition

Needed to move this to that, etc.. why I changed things
```

As for the remaining commit: `Fix port designation for postgress example` - I'm interested in the problem here. You are making a lot of changes to the service specification. I'd appreciate if you describe what is wrong in the commit message and how what you did fixes it.

**Comment by cdrage** [comment]
Hey @dustymabe 

The commit has been split again and messages have been updated reflecting the changes.

**Comment by dustymabe** [comment]
@cdrage - the new commits and related changes are MUCH easier to understand!

1st two commits look good. As for the last commit - some of the changes are related to changes in the behavior of kubernetes (changes to default behavior?)? When were these changes introduced? and can we confirm that the changes we are making still can be run on older versions of kubernetes and still behave as expected.

**Comment by cdrage** [comment]
@dustymabe 

If they're running anything lower than 1.0.0 of Kubernetes it'll (most likely) break. But that's pre-release versions.

Let me go through all of them.

**portalIP**, **clusterIP**, **sessionAffinity**, **protocol** are all set by default already by Kubernetes. No need to explicit imply them anymore hence the removal.
_For example:_
**protocol** is set to TCP by default, see: http://kubernetes.io/v1.1/docs/user-guide/services.html so we don't need it in the definition

The same goes with **port** and **targetPort**. They're both the same port, so by  http://kubernetes.io/v1.1/docs/user-guide/services.html documentation, we don't need to specify them.

**nodePort** is now automatically managed by Kubernetes (selects a randomized open port within a range) http://kubernetes.io/v1.1/docs/user-guide/services.html#type-nodeport so that no longer needs to be specified either.

After running this example on my machine I can also confirm that the service works correctly as the port is opened correctly and I am able to connect.

**Comment by dustymabe** [comment]
sounds good LGTM.

**Pull request merged**
