### PR TITLE
Update to 3.0

### PR DESCRIPTION
**Pull request by cdrage**
Any objections? Syncing everything in the library to 0.3.0

### CODE REVIEW

**Comment by dustymabe** [comment]
Is there anything about this change that we think would cause breakage? Otherwise LGTM

**Comment by cdrage** [comment]
@dustymabe don't think so. 

Any other objections? @LalatenduMohanty ?

**Comment by dustymabe** [comment]
LGTM.

**Comment by LalatenduMohanty** [comment]
@cdrage +1 LGTM

**Pull request merged**
