### PR TITLE
Sync with 0.4.1 release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by kadel** [comment]
:+1:

**Comment by kadel** [comment]
It looks like you had bug in you `sed`. :wink: 
Image name `projectatomic/atomicapp` is missing in all Dockerfiles

**Comment by cdrage** [comment]
@kadel LOLLLL

okay, updated! feel free to check again for me plz

**Comment by kadel** [comment]
:+1: :sparkles:

**Pull request merged**
