### PR TITLE
redis: update to pass in MASTER=true env var

### LINKED ISSUE #81: upcoming changes in CentOS-Dockerfiles
if https://github.com/CentOS/CentOS-Dockerfiles/pull/55 gets merged, it will possibly break https://github.com/projectatomic/nulecule-library/tree/master/redis-centos7-atomicapp

### PR DESCRIPTION
**Pull request by dustymabe**
Fixes #81

### CODE REVIEW

**Comment by dustymabe** [comment]
@goern - can you review.. Also do I need to update the centos image we are using from docker hub? 

I noticed you changed things from `redis:centos7` to `redis-28-centos7`

**Comment by cdrage** [comment]
LGTM :+1: works my end

**Comment by cdrage** [comment]
```
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

[1] 19 Apr 13:23:35.624 # Server started, Redis version 2.8.19
[1] 19 Apr 13:23:35.625 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[1] 19 Apr 13:23:35.625 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
[1] 19 Apr 13:23:35.625 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[1] 19 Apr 13:23:35.625 * The server is now ready to accept connections on port 6379
[1] 19 Apr 13:23:36.084 * Slave 172.17.0.6:6379 asks for synchronization
[1] 19 Apr 13:23:36.084 * Full resync requested by slave 172.17.0.6:6379
[1] 19 Apr 13:23:36.084 * Starting BGSAVE for SYNC with target: disk
[1] 19 Apr 13:23:36.084 * Background saving started by pid 9
[9] 19 Apr 13:23:36.096 * DB saved on disk
[9] 19 Apr 13:23:36.097 * RDB: 0 MB of memory used by copy-on-write
[1] 19 Apr 13:23:36.127 * Background saving terminated with success
[1] 19 Apr 13:23:36.127 * Synchronization with slave 172.17.0.6:6379 succeeded
```

**Comment by goern** [comment]
LGTM

@dustymabe  regarding the changed name... I dont know, to me it was just a change in the README, not changing the CentOS build pipeline, I dont know how docker.io/centos/redis gets build

**Comment by jperrin** [comment]
centos/redis repository on the dockerhub is auto-built from the CentOS-Dockerfiles github repo currently.

**Comment by dustymabe** [comment]
@jperrin right. It gets built as `redis:centos7` in docker hub - @goern changed the [README](https://github.com/CentOS/CentOS-Dockerfiles/blob/master/redis/centos7/README.md) so that the user builds his image with the tag `redis-28-centos7`. This works fine on the user's local system when building the image, but if he ever wanted to consume the one from docker hub he would need to use `redis:centos7`. This may not be obvious to the user. Should we update docker hub to build a new image name or change the readme back or do neither?

**Comment by jperrin** [comment]
How do you want to handle versioning changes in the future? Would there be a redis-29-centos in the future? I would prefer that redis:centos7  track latest, and specific versions get tagged by release version, so 28, 29 etc. Does that make sense or am I thinking about this incorrectly?

**Comment by dustymabe** [comment]
makes sense - as long as you have a plan and users reading the readme appropriately can find the image they are looking for in docker hub.

**Pull request merged**
