### PR TITLE
Sync with 0.5.1 release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by surajssd** [comment]
Can this be automated, things like this can be triggered at every release?

**Comment by cdrage** [comment]
@surajssd Yup. I use a script to do this. But I make the PR request so people can track / review it :)

**Comment by surajssd** [comment]
@cdrage sure but can this happen over CI somehow?

**Comment by cdrage** [comment]
@surajssd Yeahh... we need a test scenario for this build + test each container

**Pull request merged**
